services:
  postgres:
    image: postgres:15
    env_file: .env
    volumes:
      - chaticus-data:/var/lib/postgresql/data
      - ./Database:/docker-entrypoint-initdb.d
    networks:
      - backend

  pgadmin:
    image: dpage/pgadmin4
    env_file: .env
    ports:
      - "5050:80"
    depends_on:
      - postgres
    networks:
      - backend

  backend:
    build:
      context: ./Backend
    depends_on:
      - postgres
    networks:
      - backend

  frontend:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./Frontend:/usr/share/nginx/html
      - ./Frontend/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:

volumes:
  chaticus-data:
